#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'
echo "${GREEN}- - - - - - - - - - - - - - - - - - - - - - - - - - - -${NC}"
echo "${GREEN}Compiling TYPESCRIPT: :rocket: :bulb: ${NC}"
pnpm tsc --noEmit || {
    echo "${RED} TYPESCRIPT Compile failed: :rotating_light: :clown_face: :rotating_light:  ${NC}"
    exit 1
}
echo "${GREEN}Compile success: :white_check_mark: :money_with_wings: ${NC}"
echo "${GREEN}- - - - - - - - - - - - - - - - - - - - - - - - - - - -${NC}"

echo "${GREEN}- - - - - - - - - - - - - - - - - - - - - - - - - - - -${NC}"
echo "${GREEN}Linting files: :truck: :memo: ${NC}"
pnpm lint-staged || {
    echo "${RED}Linting failed: :fire: :clown_face::hankey: :fire: ${NC}"
    exit 1
}
echo "${GREEN}Linting success: :beers: :tada: ${NC}"
echo "${GREEN}- - - - - - - - - - - - - - - - - - - - - - - - - - - -${NC}"npx lint-staged
